dist: focal

notifications:
  slack: dat3-fall-2020:FD0Eo9xmcFuxzFmTAnpZco3x
  email: false

language: node_js

node_js: node

cache: npm

addons:
  ssh_known_hosts: 134.122.64.238

script: npm install

before_install:
- openssl aes-256-cbc -K $encrypted_db2095f63ba3_key -iv $encrypted_db2095f63ba3_iv -in deploy_rsa.enc -out deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 deploy_rsa
- ssh-add deploy_rsa

deploy:
  provider: script
  skip-cleanup: true
  script: bash ./deploy.sh
  on:
    branch: main
